### ISSUE TITLE
[MTOOLCHAINS-31] Not threadsafe for parallel execution

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-toolchains-plugin#95]
**[Hüseyin Kartal](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hsyn)** opened **[MTOOLCHAINS-31](https://issues.apache.org/jira/browse/MTOOLCHAINS-31?redirect=false)** and commented

Running maven in parallel mode result in following output which also includes TOOLCHAINS plugin.

```
*****************************************************************
* Your build is requesting parallel execution, but project      *
* contains the following plugin(s) that have goals not marked   *
* as @threadSafe to support parallel building.                  *
* While this /may/ work fine, please look for plugin updates    *
* and/or request plugins be made thread-safe.                   *
* If reporting an issue, report it against the plugin in        *
* question, not against maven-core                              *
*****************************************************************
The following plugins are not marked @threadSafe in Application component: core:
com.sun.xml.ws:jaxws-maven-plugin:2.3.2
org.apache.maven.plugins:maven-jxr-plugin:3.0.0
org.apache.maven.plugins:maven-toolchains-plugin:3.0.0
Enable debug to see more precisely which goals are not marked @threadSafe.
*****************************************************************
```

Toolchains plugin should made and/or marked threadSafe.

---

**Affects:** 3.0.0

**Remote Links:**
- [GitHub Pull Request #8
](https://github.com/apache/maven-toolchains-plugin/pull/8)

12 votes, 10 watchers

**Comment by jira-importer** [comment]
**[Ed Randall](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=edrandall)** commented

Note that only maven-toolchains-plugin is of concern here, not the other 2 plugins listed in the description:

```
07:57:54.243 [BuilderThread 0] [WARNING] *****************************************************************
07:57:54.245 [BuilderThread 0] [WARNING] The following plugins are not marked @threadSafe in my-project-build:
07:57:54.246 [BuilderThread 0] [WARNING] org.apache.maven.plugins:maven-toolchains-plugin:3.0.0
07:57:54.247 [BuilderThread 0] [WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
07:57:54.247 [BuilderThread 0] [WARNING] *****************************************************************
```

 

Goal is: `maven-toolchains-plugin:3.0.0:toolchain (default)`

This is a pretty fundamental plugin for any build pipeline in 2020, the warning is quite alarming.
We havn't noticed any particular problems around it using --threads so I'm guessing it might even be false.
It would be really handy if this could be analyzed and addressed in the next release, solution could be as simple as adding the `@threadsafe` annotation.

**Comment by jira-importer** [comment]
**[Thomas Reinhardt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER284387)** commented

I marked the plugin as threadSafe:

https://github.com/apache/maven-toolchains-plugin/pull/8

 

this is trivially correct, as the plugin has the default InstantiationStrategy (PER_LOOKUP). Also no static variables exist so no state could be shared across executions.

**Comment by cstamas** [comment]
Which issue? 3.2.0 is reported by Maven as non thread safe?

**Comment by pzygielo** [comment]
> > 3.2.0 is reported by Maven as non-thread safe?
> 
> Yes.

Which goal?

**Comment by pzygielo** [comment]
- https://github.com/apache/maven-toolchains-plugin/issues/133
